name: Clang Format

on:
  push:
  pull_request:

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Format code
        run: |
          find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\)$' -exec clang-format -style=file -i {} \;
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "style: format code with clang-format" && git push) 