name: Send Discord Message

on:
  push:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        run: |
          curl -X POST -F "content=${{ github.actor}}が${{ github.event.repository.name }}にpushした！ありがとう！%0Aコミットメッセージ：${{ github.event.head_commit.message }}" "${{ secrets.DISCORD_WEBHOOK_URL }}"